export const languageTable = {
    TR: {
        home: 'Ana Sayfa',
        launches: 'Dijital Vitrinler',
        currentLaunches: 'Yayındaki Dijital Vitrinler',
        upcomingLaunches: 'Gelecek Dijital Vitrinler',
        pastLaunches: 'Geçmiş Dijital Vitrinler',
        login: 'Giriş Yap',
        logout: 'Çıkış Yap',
        searchPlaceholder: 'Etkinlik Ara',
        learnMore: 'Daha fazlası...',
        live: 'YAYINDA',
        descriptionPlaceholder: 'Etkinlik açıklaması burada yer alacak.',
        flagCode: 'TUR',
        langCode: 'tr',
        placeholders: {
            email: 'E-posta adresinizi giriniz',
            password: 'Şifrenizi giriniz',
            remember: 'Beni Hatırla',
            loginButton: 'Giriş Yap',
            forgotPassword: 'Şifremi Unuttum',
            signUp: 'Kayıt Ol',
        },
        messages: {
            upcomingLaunch: '🚀 Bu etkinlik {date} tarihinde yayında!',
            pastLaunch: '⏰ Etkinlik {startDate} - {endDate} tarihleri arasında gerçekleşti.',
        },
        externalLinks: [
            { label: "EKOSİSTEM", href: "https://damise.com/tr/ekosistem" },
            { label: "AKADEMİ", href: "https://academy.damise.com/tr" },
            { label: "TEDARİKÇİ YÖNETİM SİSTEMİ", href: "https://damise.com/tr/tedarikci-sistemi/anketler" },
            { label: "DİJİTAL VİTRİN", href: "https://ds.damise.com/" },
            { label: "DİJİTAL LANSMAN", href: "https://dl.damise.com/" },
            { label: "İHALELER", href: "https://damise.com/tr/ihaleler" },
          ],
    },
    EN: {
        home: 'Home',
        launches: 'Events',
        currentLaunches: 'Ongoing Digital Events',
        upcomingLaunches: 'Upcoming Digital Events',
        pastLaunches: 'Past Digital Events',
        login: 'Login',
        logout: 'Logout',
        searchPlaceholder: 'Event search',
        learnMore: 'Learn more...',
        live: 'LIVE',
        descriptionPlaceholder: 'Event description will be here.',
        flagCode: 'GBR',
        langCode: 'en',
        placeholders: {
            email: 'Enter your email',
            password: 'Enter your password',
            remember: 'Remember Me',
            loginButton: 'Login',
            forgotPassword: 'Forgot Password',
            signUp: 'Sign Up',
        },
        messages: {
            upcomingLaunch: '🚀 This event will be live on {date}!',
            pastLaunch: '⏰ The event took place between {startDate} and {endDate}.',
        },
        externalLinks: [
            { label: "ECOSYSTEM", href: "https://damise.com/en/ecosystem/" },
            { label: "ACADEMY", href: "https://academy.damise.com/en" },
            { label: "SUPPLIER MANAGEMENT SYSTEM", href: "https://damise.com/en/supplier-management-system/surveys/" },
            { label: "DIGITAL SHOWCASE", href: "https://ds.damise.com/en" },
            { label: "DIGITAL LAUNCH", href: "https://dl.damise.com/en" },
            { label: "TENDERS", href: "https://damise.com/en/tenders/" },
          ],
        
    },
   
};